### ISSUE TITLE
Error when using models "jinaai/jina-embeddings-v5-text-nano" and "Alibaba-NLP/gte-base-en-v1.5"

### ISSUE THREAD

**Issue by nxchxlx** [UKPLab/sentence-transformers#3717]
#### Problem:

Models "jinaai/jina-embeddings-v5-text-nano" and "Alibaba-NLP/gte-base-en-v1.5" recently stopped working (for me).  Even with the simple code below model.encode() throws

- either an AttributeError  (`AttributeError: type object 'JinaEmbeddingsV5Model' has no attribute 'config_class'`) or a TypeError (`TypeError: transformers.models.auto.tokenization_auto.AutoTokenizer.from_pretrained() got multiple values for keyword argument 'trust_remote_code'`) for jina model 

- and IndexError (`IndexError: index 3543824036068086856 is out of bounds for dimension 0 with size 10` ) for gte model 

Other models work just fine..

#### Code:
```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer( "jinaai/jina-embeddings-v5-text-nano", trust_remote_code=True) #"Alibaba-NLP/gte-base-en-v1.5""

query_embeddings = model.encode(["Overview of climate change impacts on coastal cities"])
```

#### Versions: 
- sentence-transformers=5.4.0
- transformers=5.5.3
- torch=2.11.0
- peft=0.18.1

**Comment by tomaarsen** [comment]
Hello!

There's two separate issues at play here:
1. https://huggingface.co/Alibaba-NLP/gte-base-en-v1.5 uses custom_code from https://huggingface.co/Alibaba-NLP/new-impl for its modeling, but this implementation has not been updated to work with transformers v5. If you decrease your transformers to v4 using `pip install transformers<5`, then it should work without having to change other dependencies.
2. The https://huggingface.co/jinaai/jina-embeddings-v5-text-nano model was recently updated to work with the new Sentence Transformers v5.4 code in https://huggingface.co/jinaai/jina-embeddings-v5-text-nano/discussions/10 3 days ago, but this broke the implementation. There's a fix in https://huggingface.co/jinaai/jina-embeddings-v5-text-nano/discussions/11, which I'll ping Jina to accept. You can use `SentenceTransformer( "jinaai/jina-embeddings-v5-text-nano", trust_remote_code=True, revision="refs/pr/11")` and that should work in the meantime.

I hope this helps a bit!

- Tom Aarsen

**Comment by tomaarsen** [comment]
The fix in https://huggingface.co/jinaai/jina-embeddings-v5-text-nano/discussions/11 was merged. I'll close this as it should be mostly resolved.

- Tom Aarsen
