### ISSUE TITLE
AttributeError: 'Transformer' object has no attribute 'model_forward_params'

### ISSUE THREAD

**Issue by AmitPoonia** [UKPLab/sentence-transformers#3523]
With latest release v5.1.1, I am getting below error when embedding text using a fine tuned bi-encoder. The same model works fine with last release of v5.1.0. 

AttributeError: 'Transformer' object has no attribute 'model_forward_params'

**Comment by tomaarsen** [comment]
Hello!

I indeed introduced a `model_forward_params` attribute in the latest release, but it should always exist on the `Transformer` object. Thank you for opening this issue! 

Could you share a snippet that is failing for you? If the model is not public, then could you perhaps find a model that you can reproduce the issue with? Or alternatively, check if this script fails?

```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
embedding = model.encode("Hello world!")
print(embedding.shape)
# (384,)
```

For context, I'm not able to reproduce this at the moment.

- Tom Aarsen

**Comment by AmitPoonia** [comment]
Hi Tom,

I have the full traceback below. This was a private fine-tuned bi-encoder, according to readme file of the serialised model it was fine-tuned with sentence-transformers 5.0.0. I will try to reproduce it with freshly fine-tuned public model. 

```
Traceback (most recent call last):
  File "/Users/amitpoonia/test_project/temp.py", line 8, in <module>
    model.encode("x")
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 1094, in encode
    out_features = self.forward(features, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 1175, in forward
    input = module(input, **module_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/sentence_transformers/models/Transformer.py", line 259, in forward
    trans_features = {key: value for key, value in features.items() if key in self.model_forward_params}
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amitpoonia/test_project/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
    raise AttributeError(
AttributeError: 'Transformer' object has no attribute 'model_forward_params'
```

**Comment by AmitPoonia** [comment]
Ok, so I was able to reproduce it. Here are the steps
1. fine tune a bi-encoder using sentence-transformers version 5.0.0
2. serialise the fine-tuned model using torch like this `torch.save(model, "model.pt")`
3. load the the model for testing `model = torch.load(f"model.pt", map_location=torch.device("cpu"), weights_only=False)`
4. now it works fine for version 5.0.0 but if you update to version 5.1.1 and load the model again (as in step 3) you should see the error, the torch version is 2.8.0 

So basically this torch based serialisation and serialisation is causing this error!

**Comment by tomaarsen** [comment]
I'm able to reproduce this now! I think the core of the issue is that it's not recommended to save models with `torch.save`, but instead with `model.save_pretrained`. We can definitely resolve that though:

1. install v5.1.0 again (`pip install sentence_transformers==5.1.0`)
2. Run this script: 

```python
import torch

loaded_model = torch.load("model.pt", map_location=torch.device('cpu'), weights_only=False)
# Make sure it works as expected
embedding = loaded_model.encode("Hello world!")
print(embedding.shape)

# Let's save it in the standard Sentence Transformers format:
loaded_model.save_pretrained("finetuned-model")
```
3. install v5.1.1 again (`pip install sentence_transformers==5.1.1`)
4. load the model with:

```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("finetuned-model")
embedding = model.encode("Hello world!")
print(embedding.shape)
```

This directory (you can name it whatever you want) should continue to be loadable in all future versions, unlike if you save it with `torch.save`. 

- Tom Aarsen

**Comment by AmitPoonia** [comment]
Thanks Tom. I think I started to use torch.save because the model loading was faster with it and it was convenient to have model as one single file. But yes, probably not a good idea.

**Comment by tomaarsen** [comment]
I'll close this now, as I think it should be resolved.

- Tom Aarsen
