### ISSUE TITLE
3.2.0 release breaks CLIPModel

### ISSUE THREAD

**Issue by BoPeng** [UKPLab/sentence-transformers#3005]
After upgrading from version 3.1.1 to 3.2, loading `clip-ViT-L-14` gives the following error:

```python
>>> SentenceTransformer('clip-ViT-L-14')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 306, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1722, in _load_sbert_model
    module = module_class(model_name_or_path, cache_dir=cache_folder, backend=self.backend, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CLIPModel.__init__() got an unexpected keyword argument 'cache_dir'
```

This should be caused by the recent removal of the `try/except` block around the model loading code:

https://github.com/UKPLab/sentence-transformers/blob/29535eb44d270f5665e389aeb7e18cf04cb51bf0/sentence_transformers/SentenceTransformer.py#L1721-L1724

**Comment by PraNavKumAr01** [comment]
Same issue, did you find a fix?

**Comment by BoPeng** [comment]
Downgrading to 3.1.1 fixed the issue temporarily.

**Comment by PraNavKumAr01** [comment]
Got it, but im trying to quantize the clip model to qint8 onnx, but for that the functions are in 3.2 only

**Comment by BoPeng** [comment]
I just created a PR (#3007). Before this PR is merged, you can use my fork (e.g. use `git+https://github.com/BoPeng/sentence-transformers.git@issue3005#egg=sentence-transformers` instead of `sentence_transformers==3.2.0` in `requirements.txt`).

**Comment by ir2718** [comment]
Hi @BoPeng,

I tried installing from the source and it works as expected, so this might already be fixed elsewhere.

```python
>>> import sentence_transformers as stf
>>> from sentence_transformers import SentenceTransformer
>>> st = SentenceTransformer('clip-ViT-L-14')
>>> stf.__version__
'3.3.0.dev0'
```

**Comment by BoPeng** [comment]
You are right. I am closing the PR and will use the master branch for now.

**Comment by ir2718** [comment]
@PraNavKumAr01 

Yeah, it seems that ONNX is not supported currently for the CLIP model. In the meantime, if you are okay with using other libraries, check out this issue https://github.com/mlfoundations/open_clip/issues/186, and this repo https://github.com/jina-ai/clip-as-service.
